name: Deploy
on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Build step
        env:
          PASSWORD_API: ${{ secrets.PASSWORD_API }}
          PUBLIC_TEST_SECRET: ${{ secrets.PUBLIC_TEST_SECRET }}
        run: "npm install --legacy-peer-deps && npm run build" # 📝 Update the build command(s) if necessary

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: ambisonics-syntia
          entrypoint: server/entry.mjs
          root: dist
